FROM debian:12-slim as rootfs

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt update && \
    apt install -y --no-install-recommends \
        ca-certificates \
        curl

RUN curl -o /tmp/rootfs.tar.gz -L https://pub-1a5aeef625fc45b4a4bef89ee141047f.r2.dev/debian-bookworm-systemd-rootfs.tar.gz
RUN mkdir -p /rootfs && tar -C /rootfs -xzf /tmp/rootfs.tar.gz

FROM scratch

COPY --from=rootfs /rootfs /

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt update && \
    apt install -y --no-install-recommends \
        ca-certificates \
        curl \
        gnupg && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install containerd
RUN curl -OL https://github.com/containerd/containerd/releases/download/v1.7.2/containerd-1.7.2-linux-amd64.tar.gz && \
    tar Cxzvf /usr/local containerd-1.7.2-linux-amd64.tar.gz && \
    ln -sf /etc/systemd/system/containerd.service /etc/systemd/system/multi-user.target.wants/containerd.service

# Install CNI plugins
RUN curl -OL https://github.com/containernetworking/plugins/releases/download/v1.3.0/cni-plugins-linux-amd64-v1.3.0.tgz && \
    mkdir -p /opt/cni/bin && \
    tar Cxzvf /opt/cni/bin cni-plugins-linux-amd64-v1.3.0.tgz

# Install runc
RUN curl -OL https://github.com/opencontainers/runc/releases/download/v1.1.7/runc.amd64 && \
    chmod +x runc.amd64 && \
    install -m 755 runc.amd64 /usr/local/sbin/runc

# Install kubeadm, kubelet, kubectl
RUN curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list && \
    apt update && \
    apt install -y kubelet kubeadm kubectl && \
    apt-mark hold kubelet kubeadm kubectl

COPY firework-dev/k8s/config.toml /etc/containerd/config.toml
COPY firework-dev/k8s/containerd.service /etc/systemd/system/containerd.service
COPY firework-dev/fwagent.service artifacts/firework-agent .

RUN update-alternatives --set iptables /usr/sbin/iptables-legacy && \
    update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

RUN mkdir -p /overlay /mnt /rom

COPY firework-dev/overlay-init-systemd /sbin/overlay-init-systemd

RUN cp fwagent.service /etc/systemd/system/fwagent.service && \
    ln -sf /etc/systemd/system/fwagent.service /etc/systemd/system/multi-user.target.wants/fwagent.service && \
    cp firework-agent /usr/bin/fwagent