#!/bin/sh

set -eu

function die {
    echo "Error: $1"
    exit 1
}

function pivot {
    local rw_root work_dir

    rw_root="$1"
    work_dir="$2"

    /bin/mount \
	    -o noatime,lowerdir=/,upperdir=${rw_root},workdir=${work_dir} \
	    -t overlay "overlayfs:${rw_root}" /mnt

    pivot_root /mnt /mnt/rom || exit 1
}

# Overlay is configured under /overlay
function do_overlay {
    local overlay_dir="/overlay"

    if [ "$overlay_root" = "ram" ] ||
           [ -z "$overlay_root" ]; then
        /bin/mount -t tmpfs -o noatime,mode=0755 tmpfs /overlay
    else
        /bin/mount -t ext4 "/dev/$overlay_root" /overlay
    fi

    mkdir -p /overlay/root /overlay/work
    pivot /overlay/root /overlay/work
}

# If we're given an overlay, ensure that it really exists. Panic if not.
if [ -n "$overlay_root" ] &&
       [ "$overlay_root" != ram ] &&
       [ ! -b "/dev/$overlay_root" ]; then
    echo -n "FATAL: "
    echo "Overlay root given as $overlay_root but /dev/$overlay_root does not exist"
    exit 1
fi

echo "[OVERLAY_INIT] Trying to mount /dev/$overlay_root and setup overlayfs on /overlay..."

do_overlay
chdir /

echo "[OVERLAY_INIT] overlayfs successfully created"

# touch /etc/hosts

chmod_0755="u=rwx,g=rx,o=rx"
chmod_0555="u=r-x,g=rx,o=rx"
chmod_1777="u=rwx,g=rwx,o=rwx"
common_mnt_flags="nodev,noexec,nosuid"
common_cgroup_mnt_flags="nodev,noexec,nosuid,relatime"

# Move mount point of devtmpfs so we don't have to remount it
/bin/mount --move /rom/dev /dev

function mount_filesystems {
    mkdir -p -m $chmod_0755 /dev/pts || die "Failed to create /dev/pts directory"
    /bin/mount -t devpts -o "newinstance,gid=5,mode=620,ptmxmode=666" devpts /dev/pts || die "Failed to mount /dev/pts"
    echo "[OVERLAY_INIT] Mounted /dev/pts"

    mkdir -p -m $chmod_0755 /dev/mqueue || die "Failed to create /dev/mqueue directory"
    /bin/mount -t mqueue -o $common_mnt_flags mqueue /dev/mqueue || die "Failed to mount /dev/mqueue"
    echo "[OVERLAY_INIT] Mounted /dev/mqueue"

    mkdir -p -m $chmod_1777 /dev/shm || die "Failed to create /dev/shm directory"
    /bin/mount -t tmpfs -o "nosuid,nodev" tmpfs /dev/shm || die "Failed to mount /dev/shm"
    echo "[OVERLAY_INIT] Mounted /dev/shm"

    mkdir -p -m $chmod_0755 /dev/hugepages || die "Failed to create /dev/hugepages directory"
    /bin/mount -t hugetlbfs -o "relatime,pagesize=2M" hugetlbfs /dev/hugepages || die "Failed to mount /dev/hugepages"
    echo "[OVERLAY_INIT] Mounted /dev/hugepages"

    mkdir -p -m $chmod_0555 /proc || die "Failed to create /proc directory"
    /bin/mount -t proc -o $common_mnt_flags proc /proc || die "Failed to mount /proc"
    /bin/mount -t binfmt_misc -o $common_mnt_flags,relatime binfmt_misc /proc/sys/fs/binfmt_misc || die "Failed to mount /proc/sys/fs/binfmt_misc"
    echo "[OVERLAY_INIT] Mounted /proc"

    mkdir -p -m $chmod_0555 /sys || die "Failed to create /sys directory"
    /bin/mount -t sysfs -o $common_mnt_flags sysfs /sys || die "Failed to mount /sys"
    echo "[OVERLAY_INIT] Mounted /sys"

    mkdir -p -m $chmod_0755 /run || die "Failed to create /run directory"
    /bin/mount -t tmpfs -o "nosuid,nodev" tmpfs /run || die "Failed to mount /run"
    mkdir -p -m $chmod_0755 /run/lock || die "Failed to create /run/lock directory"
    echo "[OVERLAY_INIT] Mounted /run"

    symlink="/proc/self/fd"
    ln -s $symlink /dev/fd || die "Failed to create symlink /dev/fd"
    ln -s "$symlink/0" /dev/stdin || die "Failed to create symlink /dev/stdin"
    ln -s "$symlink/1" /dev/stdout || die "Failed to create symlink /dev/stdout"
    ln -s "$symlink/2" /dev/stderr || die "Failed to create symlink /dev/stderr"
    echo "[OVERLAY_INIT] Created symlinks to /proc/self/fd"

    mkdir -p -m $chmod_0755 /root || die "Failed to create /root directory"
    echo "[OVERLAY_INIT] Created /root directory"

    /bin/mount -t tmpfs -o "nosuid,noexec,nodev" tmpfs /sys/fs/cgroup || die "Failed to mount /sys/fs/cgroup"
    echo "[OVERLAY_INIT] Mounted cgroup"

    mkdir -p -m $chmod_0555 /sys/fs/cgroup/unified || die "Failed to create /sys/fs/cgroup/unified directory"
    /bin/mount -t cgroup2 -o "$common_mnt_flags,relatime,nsdelegate" cgroup2 /sys/fs/cgroup/unified || die "Failed to mount /sys/fs/cgroup/unified"
    echo "[OVERLAY_INIT] Mounted cgroup2"
}

echo -e "\n[OVERLAY_INIT] Mounting filesystems..."
mount_filesystems
echo -e "[OVERLAY_INIT] Finished mounting filesystems\n"

umount -l /rom
rmdir rom

echo -e "[OVERLAY_INIT] Handing off the rest to init...\n"
exec /init /firework-agent