#!/bin/sh
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may
# not use this file except in compliance with the License. A copy of the
# License is located at
#
#       http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# Parameters:
# 1. rw_root -- path where the read/write root is mounted
# 2. work_dir -- path to the overlay workdir (must be on same filesystem as rw_root)
# Overlay will be set up on /mnt, original root on /mnt/rom
pivot() {
    local rw_root work_dir
    rw_root="$1"
    work_dir="$2"
    /bin/mount \
	-o noatime,lowerdir=/,upperdir=${rw_root},workdir=${work_dir} \
	-t overlay "overlayfs:${rw_root}" /mnt
    pivot_root /mnt /mnt/rom
    echo "Pivoted root"
}

# Overlay is configured under /overlay
do_overlay() {
    /bin/mount -t tmpfs -o noatime,mode=0755 tmpfs /overlay
    mkdir -p /overlay/root /overlay/work
    pivot /overlay/root /overlay/work
}

do_overlay

# Move mount point of devtmpfs so we don't have to remount it
# /bin/mount -t devtmpfs -o remount,ro none /dev
/bin/mount --move /rom/dev /dev

# Invoke the actual system init program and procede with the boot
# process.

exec chroot . /sbin/init $@