FROM debian:12-slim as rootfs

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt update && \
    apt install -y --no-install-recommends \
        ca-certificates \
        curl

RUN curl -o /tmp/rootfs.tar.gz -L https://pub-1a5aeef625fc45b4a4bef89ee141047f.r2.dev/debian-bookworm-systemd-rootfs.tar.gz
RUN mkdir -p /rootfs && tar -C /rootfs -xzf /tmp/rootfs.tar.gz

FROM scratch

# ARG ROOTFS_ARCHIVE_PATH

# ADD $ROOTFS_ARCHIVE_PATH /

COPY --from=rootfs /rootfs /

ARG FC_RELEASE=firecracker-v1.3.3-x86_64

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt update && \
    apt install -y --no-install-recommends \
        ca-certificates \
        curl \
        gnupg && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN curl -o /tmp/$FC_RELEASE.tgz -L https://github.com/firecracker-microvm/firecracker/releases/download/v1.3.3/$FC_RELEASE.tgz && \
    tar -xvf /tmp/$FC_RELEASE.tgz -C /tmp && \
    cp /tmp/release-v1.3.3-x86_64/$FC_RELEASE /usr/bin/firecracker
