# syntax=docker/dockerfile:1.3-labs

FROM gcr.io/distroless/cc-debian11

WORKDIR /firework

# COPY config config
# COPY kernel kernel
# COPY vm vm
# COPY macgen.py .
# COPY *.sh .
# COPY Dockerfile .
# COPY .gitignore .
# COPY custom-init /sbin/init
