FROM scratch

ADD rootfs /

RUN apk update \
	&& apk add openrc openssh sudo util-linux curl iptables dnsmasq e2fsprogs buildkit buildkit-openrc bash  \
	&& ssh-keygen -A \
	&& ln -s agetty /etc/init.d/agetty.ttyS0 \
	&& echo ttyS0 > /etc/securetty \
	&& rc-update add agetty.ttyS0 default \
    && rc-update add buildkitd default \
	&& rc-update add devfs boot \
	&& rc-update add procfs boot \
	&& rc-update add sysfs boot \
    && rc-update add cgroups boot \
    && rc-update add networking sysinit \
	&& rc-update add local default

RUN curl -OL https://github.com/opencontainers/runc/releases/download/v1.1.7/runc.amd64 && \
    chmod +x runc.amd64 && \
    mv runc.amd64 /usr/local/bin/runc

RUN curl -OL https://github.com/moby/buildkit/releases/download/v0.11.6/buildkit-v0.11.6.linux-amd64.tar.gz && \
    tar -xvf buildkit-v0.11.6.linux-amd64.tar.gz -C /usr/local

RUN mkdir -p /run/openrc \
	&& touch /run/openrc/softlevel \
	&& rc-update add sshd \
    && rc-update add dnsmasq default

# configure sshd
RUN sed -i 's/^#\(PermitRootLogin\) .*/\1 yes/' /etc/ssh/sshd_config && \
    sed -i 's/^#\(PasswordAuthentication\) .*/\1 no/' /etc/ssh/sshd_config

WORKDIR /firework
COPY . .